/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_24022026;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        //no hay elementos visuales
        initComponents(); //se estan creando los elementos visuales 
        // ya se crearon los elementos visuales peor aun no se renderizan en pantalla
        tabPane_pestanas.setVisible(false);
        
        //creando el modelo para usar en los comboboxes 
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        jcb_editarUsuarios.setModel(modelo);
        jcb_comboBoxEliminar.setModel(modelo);
        jcb_comboBoxMostrar.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane_pestanas = new javax.swing.JTabbedPane();
        jp_agregar = new javax.swing.JPanel();
        lbl_agregarNombre = new javax.swing.JLabel();
        txt_agregarNombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcb_tipoPersona = new javax.swing.JComboBox<>();
        jp_eliminar = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        jcb_comboBoxEliminar = new javax.swing.JComboBox<>();
        jp_editar = new javax.swing.JPanel();
        lbl_editNombre = new javax.swing.JLabel();
        txt_editNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcb_comboBoxEditar = new javax.swing.JComboBox<>();
        jcb_editarUsuarios = new javax.swing.JComboBox<>();
        btn_actualizarDatos = new javax.swing.JButton();
        jp_mostrar = new javax.swing.JPanel();
        lbl_mostrar = new javax.swing.JLabel();
        lbl_mostrarNombre = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        lbl_mostrarTipo = new javax.swing.JLabel();
        jcb_comboBoxMostrar = new javax.swing.JComboBox<>();
        jp_login = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_agregarNombre.setText("Nombre");

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("Tipo");

        jcb_tipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));

        javax.swing.GroupLayout jp_agregarLayout = new javax.swing.GroupLayout(jp_agregar);
        jp_agregar.setLayout(jp_agregarLayout);
        jp_agregarLayout.setHorizontalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton2))
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_agregarNombre)
                            .addComponent(jLabel1))
                        .addGap(78, 78, 78)
                        .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_agregarNombre)
                            .addComponent(jcb_tipoPersona, 0, 371, Short.MAX_VALUE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jp_agregarLayout.setVerticalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agregarNombre)
                    .addComponent(txt_agregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcb_tipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        tabPane_pestanas.addTab("Agregar", jp_agregar);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        jcb_comboBoxEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_comboBoxEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_comboBoxEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarLayout = new javax.swing.GroupLayout(jp_eliminar);
        jp_eliminar.setLayout(jp_eliminarLayout);
        jp_eliminarLayout.setHorizontalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGroup(jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btn_eliminar))
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jcb_comboBoxEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jp_eliminarLayout.setVerticalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_eliminarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jcb_comboBoxEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(55, 55, 55))
        );

        tabPane_pestanas.addTab("Eliminar", jp_eliminar);

        lbl_editNombre.setText("Nombre");

        jLabel2.setText("Tipo");

        jcb_comboBoxEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));

        jcb_editarUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_editarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_editarUsuariosActionPerformed(evt);
            }
        });

        btn_actualizarDatos.setText("Actualizar");
        btn_actualizarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarDatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_editarLayout = new javax.swing.GroupLayout(jp_editar);
        jp_editar.setLayout(jp_editarLayout);
        jp_editarLayout.setHorizontalGroup(
            jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_editarLayout.createSequentialGroup()
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_editarLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_editNombre)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_editNombre)
                            .addComponent(jcb_comboBoxEditar, 0, 205, Short.MAX_VALUE)))
                    .addGroup(jp_editarLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jcb_editarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_editarLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btn_actualizarDatos)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jp_editarLayout.setVerticalGroup(
            jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_editarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_editarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_editNombre)
                    .addComponent(txt_editNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_comboBoxEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btn_actualizarDatos)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        tabPane_pestanas.addTab("Editar", jp_editar);

        lbl_mostrar.setText("Nombre");

        lbl_tipo.setText("Tipo");

        jcb_comboBoxMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_comboBoxMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_comboBoxMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_mostrarLayout = new javax.swing.GroupLayout(jp_mostrar);
        jp_mostrar.setLayout(jp_mostrarLayout);
        jp_mostrarLayout.setHorizontalGroup(
            jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mostrarLayout.createSequentialGroup()
                .addGroup(jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mostrarLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_mostrarLayout.createSequentialGroup()
                                .addComponent(lbl_tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_mostrarTipo))
                            .addGroup(jp_mostrarLayout.createSequentialGroup()
                                .addComponent(lbl_mostrar)
                                .addGap(93, 93, 93)
                                .addComponent(lbl_mostrarNombre))))
                    .addGroup(jp_mostrarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jcb_comboBoxMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jp_mostrarLayout.setVerticalGroup(
            jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mostrarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mostrar)
                    .addComponent(lbl_mostrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jp_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipo)
                    .addComponent(lbl_mostrarTipo))
                .addGap(62, 62, 62)
                .addComponent(jcb_comboBoxMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tabPane_pestanas.addTab("Mostrar", jp_mostrar);

        btn_login.setText("LOGIN");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_loginLayout = new javax.swing.GroupLayout(jp_login);
        jp_login.setLayout(jp_loginLayout);
        jp_loginLayout.setHorizontalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_loginLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btn_login)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jp_loginLayout.setVerticalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabPane_pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tabPane_pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
       DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_comboBoxEliminar.getModel();
       int seleccionado = jcb_comboBoxEliminar.getSelectedIndex();
       modelo.removeElementAt(seleccionado);
       JOptionPane.showMessageDialog(null,"Usuario Eliminado!");
       
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
     tabPane_pestanas.setVisible(true);
     jp_login.setVisible(false);
     
     // deshabilitar 
     // pos tab , habilitado/deshabilitado
//     tabPane_pestanas.setEnabledAt(1, false);
//     tabPane_pestanas.setEnabledAt(2, false);
//     tabPane_pestanas.setEnabledAt(3, false);

     // ocultar una pestana
       tabPane_pestanas.remove(3);
       tabPane_pestanas.remove(2);
       tabPane_pestanas.remove(1);
    }//GEN-LAST:event_btn_loginMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

       
       //habilitar tabs 
//      tabPane_pestanas.setEnabledAt(1, true);
//     tabPane_pestanas.setEnabledAt(2, true);
//     tabPane_pestanas.setEnabledAt(3, true);
     
     // agregar /mostrar tabs
        tabPane_pestanas.addTab("Mostrar", jp_mostrar);
        tabPane_pestanas.addTab("Editar", jp_editar);
       tabPane_pestanas.addTab("Eliminar", jp_eliminar);
       //creando el objeto 
       String nombre = txt_agregarNombre.getText();
       int tipo = jcb_tipoPersona.getSelectedIndex();
       Persona nuevapersona = new Persona(nombre,tipo);
        System.out.println(nuevapersona);
        JOptionPane.showMessageDialog(this, "Persona creada exitosamente");
        // agregar el objeto al combobox 

      DefaultComboBoxModel modelo = (DefaultComboBoxModel)  jcb_editarUsuarios.getModel();
       modelo.addElement(nuevapersona);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jcb_comboBoxEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_comboBoxEliminarActionPerformed
        
    }//GEN-LAST:event_jcb_comboBoxEliminarActionPerformed

    private void jcb_comboBoxMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_comboBoxMostrarActionPerformed
//        System.out.println(jcb_comboBoxMostrar.getSelectedIndex());
        Persona persona = (Persona)jcb_comboBoxMostrar.getSelectedItem();
        lbl_mostrarNombre.setText(persona.getNombre());
        lbl_mostrarTipo.setText(persona.getTipo()+"");
    }//GEN-LAST:event_jcb_comboBoxMostrarActionPerformed

    private void jcb_editarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_editarUsuariosActionPerformed
    Persona persona = (Persona)jcb_editarUsuarios.getSelectedItem();
    txt_editNombre.setText(persona.getNombre());
    jcb_comboBoxEditar.setSelectedIndex(persona.getTipo());
    
        
    }//GEN-LAST:event_jcb_editarUsuariosActionPerformed

    private void btn_actualizarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarDatosMouseClicked
        Persona persona = (Persona)jcb_editarUsuarios.getSelectedItem();
        String nombre = txt_editNombre.getText();
        int tipo  = jcb_comboBoxEditar.getSelectedIndex();
        persona.setNombre(nombre);
        persona.setTipo(tipo);
        JOptionPane.showMessageDialog(null,"Informcion actualizada");
        
    }//GEN-LAST:event_btn_actualizarDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarDatos;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcb_comboBoxEditar;
    private javax.swing.JComboBox<String> jcb_comboBoxEliminar;
    private javax.swing.JComboBox<String> jcb_comboBoxMostrar;
    private javax.swing.JComboBox<String> jcb_editarUsuarios;
    private javax.swing.JComboBox<String> jcb_tipoPersona;
    private javax.swing.JPanel jp_agregar;
    private javax.swing.JPanel jp_editar;
    private javax.swing.JPanel jp_eliminar;
    private javax.swing.JPanel jp_login;
    private javax.swing.JPanel jp_mostrar;
    private javax.swing.JLabel lbl_agregarNombre;
    private javax.swing.JLabel lbl_editNombre;
    private javax.swing.JLabel lbl_mostrar;
    private javax.swing.JLabel lbl_mostrarNombre;
    private javax.swing.JLabel lbl_mostrarTipo;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JTabbedPane tabPane_pestanas;
    private javax.swing.JTextField txt_agregarNombre;
    private javax.swing.JTextField txt_editNombre;
    // End of variables declaration//GEN-END:variables
}
