/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_18022026;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    // Constructor
    public Principal() {
        //antes de llamar el metodo init components No tenemos elementos mostrandose en pantalla
        initComponents(); // se encarga de renderizar los elemtnos en la pantalla 
        // Despues de este metodo, si tenemos elementos visuales en la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombre = new javax.swing.JLabel();
        btn_mostrarSaludo = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        lbl_saludo = new javax.swing.JLabel();
        lbl_oculta = new javax.swing.JLabel();
        txt_oculta = new javax.swing.JTextField();
        btn_mostrar = new javax.swing.JButton();
        btn_ocultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nombre.setBackground(new java.awt.Color(255, 153, 102));
        lbl_nombre.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbl_nombre.setText("Noombre");

        btn_mostrarSaludo.setBackground(new java.awt.Color(255, 204, 204));
        btn_mostrarSaludo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_mostrarSaludo.setText("Cambiar texto");
        btn_mostrarSaludo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarSaludoMouseClicked(evt);
            }
        });

        lbl_saludo.setText("Hola! ");

        lbl_oculta.setBackground(new java.awt.Color(255, 153, 102));
        lbl_oculta.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbl_oculta.setText("Campo Oculto");

        btn_mostrar.setText("Mostrar Campo Oculto");
        btn_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarMouseClicked(evt);
            }
        });

        btn_ocultar.setText("Ocuktar Campo oculto");
        btn_ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ocultarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lbl_saludo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addGap(72, 72, 72)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_oculta)
                                    .addComponent(btn_mostrarSaludo))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_oculta, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_ocultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_mostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_oculta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_oculta))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrarSaludo)
                    .addComponent(btn_mostrar))
                .addGap(29, 29, 29)
                .addComponent(btn_ocultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lbl_saludo)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarSaludoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarSaludoMouseClicked
//        txt_nombre variable que contiene el objeto del textfield (donde ingresmos texto)
//         lbl_saludo       variable que contiene el objeto del label (donde se muestra texto)
        String textoIngresado = txt_nombre.getText();
        lbl_saludo.setText(textoIngresado);
//         lbl_saludo.setText(txt_nombre.getText());


        
    }//GEN-LAST:event_btn_mostrarSaludoMouseClicked

    private void btn_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarMouseClicked
           txt_oculta.setVisible(true);
       lbl_oculta.setVisible(true);
    }//GEN-LAST:event_btn_mostrarMouseClicked

    private void btn_ocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ocultarMouseClicked
       txt_oculta.setVisible(false);
       lbl_oculta.setVisible(false);
    }//GEN-LAST:event_btn_ocultarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton btn_mostrarSaludo;
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_oculta;
    private javax.swing.JLabel lbl_saludo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_oculta;
    // End of variables declaration//GEN-END:variables
}
