/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_02032026;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultListModel modeloLista = new DefaultListModel();
        jl_listaPersonas.setModel(modeloLista); 
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jt_tablaInformacion.setModel(modeloTabla);
        
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Tipo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_pantalla = new javax.swing.JDialog();
        lbl_dialog = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jpm_menuEmergente = new javax.swing.JPopupMenu();
        jmi_limpiar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jpm_menu2 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_agregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_agregarNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jc_tipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaPersonas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombreSeleccionado = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        lbl_texto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_contenido = new javax.swing.JTextField();
        btn_colorTexto = new javax.swing.JButton();
        txt_tamano = new javax.swing.JTextField();
        jcb_estilo = new javax.swing.JComboBox<>();
        btn_guardarContenido = new javax.swing.JButton();
        btn_guardarTamano = new javax.swing.JButton();
        btn_cambiarColorbackground = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_fuente = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_tablaInformacion = new javax.swing.JTable();
        btn_agregarColumna = new javax.swing.JButton();
        lbl_nombreTabla = new javax.swing.JLabel();
        lbl_apellidoTabla = new javax.swing.JLabel();
        lbl_tipoTabla = new javax.swing.JLabel();
        lbl_columna = new javax.swing.JLabel();
        lbl_fila = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_editarTabla = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jmb_menuPrincipal = new javax.swing.JMenuBar();
        jm_abrir = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jm_exportar = new javax.swing.JMenu();

        lbl_dialog.setText("TEXTO DE EJEMPLO");
        lbl_dialog.setOpaque(true);

        jButton4.setText("Reset Info");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_pantallaLayout = new javax.swing.GroupLayout(jd_pantalla.getContentPane());
        jd_pantalla.getContentPane().setLayout(jd_pantallaLayout);
        jd_pantallaLayout.setHorizontalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(lbl_dialog))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jd_pantallaLayout.setVerticalGroup(
            jd_pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pantallaLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lbl_dialog)
                .addGap(63, 63, 63)
                .addComponent(jButton4)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jmi_limpiar.setText("Limpiar");
        jpm_menuEmergente.add(jmi_limpiar);

        jMenuItem4.setText("jMenuItem4");
        jpm_menuEmergente.add(jMenuItem4);

        jMenu2.setText("jMenu2");
        jpm_menu2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setText("Apellido");

        jc_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario Regular" }));

        jLabel9.setText("Tipo");

        javax.swing.GroupLayout jp_agregarLayout = new javax.swing.GroupLayout(jp_agregar);
        jp_agregar.setLayout(jp_agregarLayout);
        jp_agregarLayout.setHorizontalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1))
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(71, 71, 71)
                        .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jc_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_agregarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(txt_apellido))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jp_agregarLayout.setVerticalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_agregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jp_agregar);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jl_listaPersonas.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 10)); // NOI18N
        jl_listaPersonas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jl_listaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listaPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_listaPersonas);

        jLabel2.setText("Nombre");

        lbl_nombreSeleccionado.setText("jLabel3");

        jButton2.setText("eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(lbl_nombreSeleccionado)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_nombreSeleccionado))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista", jPanel1);

        jScrollPane3.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel3);

        lbl_texto.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        lbl_texto.setText("jLabel3");
        lbl_texto.setOpaque(true);

        jLabel3.setText("Contenido");

        jLabel4.setText("Color");

        jLabel5.setText("Tamano");

        jLabel6.setText("Estilo");

        txt_contenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_contenidoMouseClicked(evt);
            }
        });

        btn_colorTexto.setText("Color Texto");
        btn_colorTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_colorTextoMouseClicked(evt);
            }
        });

        jcb_estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Negrita", "Italica" }));
        jcb_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_estiloActionPerformed(evt);
            }
        });

        btn_guardarContenido.setText("Guardar");
        btn_guardarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarContenidoMouseClicked(evt);
            }
        });

        btn_guardarTamano.setText("Guardar");
        btn_guardarTamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarTamanoMouseClicked(evt);
            }
        });

        btn_cambiarColorbackground.setText("Color background");
        btn_cambiarColorbackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cambiarColorbackgroundMouseClicked(evt);
            }
        });

        jLabel7.setText("Fuente");

        jButton3.setText("Guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(btn_colorTexto))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(txt_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_guardarContenido)
                            .addComponent(btn_cambiarColorbackground)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_fuente))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_guardarTamano)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jcb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(lbl_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_texto)
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardarContenido))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_colorTexto)
                    .addComponent(btn_cambiarColorbackground))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_guardarTamano))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Texto", jPanel4);

        jt_tablaInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_tablaInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tablaInformacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_tablaInformacion);

        btn_agregarColumna.setText("Agregar Columna");
        btn_agregarColumna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarColumnaMouseClicked(evt);
            }
        });

        lbl_nombreTabla.setText("jLabel10");

        lbl_apellidoTabla.setText("jLabel11");

        lbl_tipoTabla.setText("jLabel12");

        lbl_columna.setText("jLabel10");

        lbl_fila.setText("jLabel11");

        btn_eliminar.setText("Eliminar fila ");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_editarTabla.setText("Editar Fila");
        btn_editarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarTablaMouseClicked(evt);
            }
        });

        jLabel10.setText("fila");

        jLabel11.setText("columna");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nombreTabla)
                                    .addComponent(btn_eliminar))
                                .addGap(129, 129, 129)
                                .addComponent(lbl_apellidoTabla))
                            .addComponent(btn_editarTabla))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tipoTabla, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_agregarColumna, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_fila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_columna)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreTabla)
                    .addComponent(lbl_apellidoTabla)
                    .addComponent(lbl_tipoTabla))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarColumna)
                    .addComponent(btn_editarTabla)
                    .addComponent(btn_eliminar)
                    .addComponent(lbl_fila)
                    .addComponent(lbl_columna))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel2);

        jm_abrir.setText("Abrir");

        jMenu1.setText("SubMenu");

        jMenuItem1.setText("Mostrar Pantalla");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jm_abrir.add(jMenu1);

        jMenuItem2.setText("Opcion");
        jm_abrir.add(jMenuItem2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jm_abrir.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jm_abrir.add(jRadioButtonMenuItem1);
        jm_abrir.add(jSeparator1);

        jMenuItem3.setText("jMenuItem3");
        jm_abrir.add(jMenuItem3);

        jmb_menuPrincipal.add(jm_abrir);

        jm_exportar.setText("Exportar");
        jmb_menuPrincipal.add(jm_exportar);

        setJMenuBar(jmb_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      String nombre = txt_agregarNombre.getText();
      String apellido = txt_apellido.getText();
      String tipo = jc_tipo.getSelectedItem().toString();
      
      Persona p = new Persona(nombre,apellido,tipo);
      
      // agregando a la lista
      DefaultListModel modelo = (DefaultListModel)jl_listaPersonas.getModel();
      modelo.addElement(p);
      
      //agregar a la tabla
     DefaultTableModel modeloTabla = (DefaultTableModel)jt_tablaInformacion.getModel();
     Object [] elementos =  {p.getNombre(),p.getApellido(),p.getTipo()};
     modeloTabla.addRow(elementos);
      
      // agregar al arbol 
      
      
      
       JOptionPane.showMessageDialog(this, "Objeto agregado exitosamente");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jl_listaPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listaPersonasMouseClicked
        
        switch (evt.getButton()) {
            case MouseEvent.BUTTON1: //izquierdo
                    DefaultListModel modelo = (DefaultListModel)jl_listaPersonas.getModel();
                    int index = jl_listaPersonas.getSelectedIndex();
                    Object seleccionado = modelo.getElementAt(index);

                   Persona p = (Persona)seleccionado;
                  lbl_nombreSeleccionado.setText(p.getNombre());
                break;
            case MouseEvent.BUTTON2:// scroll 
                System.out.println("Scroll");
                break;
            case MouseEvent.BUTTON3: //derecho
                jpm_menuEmergente.show(jl_listaPersonas, evt.getX(), evt.getY());
                break;
                
        }
// Ejemplo obtener el objeto directamente 
//       Object seleccionado = jl_listaPersonas.getSelectedValue();
       
// Ejemplo, obtener el objeto usando el index 


    }//GEN-LAST:event_jl_listaPersonasMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      int index = jl_listaPersonas.getSelectedIndex();
      if(index==-1){
           JOptionPane.showMessageDialog(this, "Debe seleccionar un elementos antes de poderf realizar esta accion");
      }else{
          DefaultListModel modelo = (DefaultListModel)jl_listaPersonas.getModel();
          modelo.remove(index);
        JOptionPane.showMessageDialog(this, "Elemento eliminado");
      }
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_guardarContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarContenidoMouseClicked
//       String texto = txt_contenido.getText();
//       lbl_texto.setText(texto);
        lbl_texto.setText(txt_contenido.getText());
        lbl_dialog.setText(txt_contenido.getText());
    }//GEN-LAST:event_btn_guardarContenidoMouseClicked

    private void btn_colorTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_colorTextoMouseClicked
       Color seleccionado = JColorChooser.showDialog(null, "Seeleccione un color para el texto", Color.GREEN);
       lbl_texto.setForeground(seleccionado);
       lbl_dialog.setForeground(seleccionado);
        
    }//GEN-LAST:event_btn_colorTextoMouseClicked

    private void btn_cambiarColorbackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cambiarColorbackgroundMouseClicked
           Color seleccionado = JColorChooser.showDialog(null, "Seeleccione un color para el texto", Color.GREEN);
            lbl_texto.setBackground(seleccionado);
            lbl_dialog.setBackground(seleccionado);
    }//GEN-LAST:event_btn_cambiarColorbackgroundMouseClicked

    private void btn_guardarTamanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarTamanoMouseClicked
       int tamano = Integer.parseInt(txt_tamano.getText());
       Font vieja = lbl_texto.getFont();
       Font nueva = new Font(vieja.getFamily(), vieja.getStyle(),tamano);
        lbl_texto.setFont(nueva);
        lbl_dialog.setFont(nueva);
    }//GEN-LAST:event_btn_guardarTamanoMouseClicked

    private void jcb_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_estiloActionPerformed
         Font vieja = lbl_texto.getFont();
         int estilo = 0;
        switch (jcb_estilo.getSelectedIndex()) {
            case 0: // normal
                estilo = Font.PLAIN;
                break;
            case 1: //Negrita 
                 estilo = Font.BOLD;
                break;
            case 2: //Italico
                 estilo = Font.ITALIC;
                break;
        }

          Font nueva = new Font(vieja.getFamily(), estilo,vieja.getSize());
          lbl_texto.setFont(nueva);
          lbl_dialog.setFont(nueva);
    }//GEN-LAST:event_jcb_estiloActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       String fuente = txt_fuente.getText();
        Font vieja = lbl_texto.getFont();
        Font nueva = new Font(fuente, vieja.getStyle(),vieja.getSize());
        lbl_texto.setFont(nueva);
        lbl_dialog.setFont(nueva);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    jd_pantalla.setVisible(true);
    jd_pantalla.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txt_contenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contenidoMouseClicked
        
    }//GEN-LAST:event_txt_contenidoMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
               txt_contenido.setText("");
               txt_tamano.setText("");
               txt_fuente.setText("");
               jcb_estilo.setSelectedIndex(0);
               Font nueva = new Font("Times New Roman", Font.PLAIN,12);
               lbl_texto.setFont(nueva);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
              
        switch (evt.getButton()) {
            case MouseEvent.BUTTON1: //izquierdo
                    jpm_menu2.show(jl_listaPersonas, evt.getX(), evt.getY());
                break;
            case MouseEvent.BUTTON2:// scroll 
                System.out.println("Scroll");
                break;
            case MouseEvent.BUTTON3: //derecho
                jmi_limpiar.setEnabled(false);
                jmi_limpiar.setVisible(false);
                jpm_menuEmergente.show(jl_listaPersonas, evt.getX(), evt.getY());
                break;
                
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btn_agregarColumnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarColumnaMouseClicked
         DefaultTableModel modeloTabla = (DefaultTableModel)jt_tablaInformacion.getModel();
        
        modeloTabla.addColumn("NuevaColumna!");
    }//GEN-LAST:event_btn_agregarColumnaMouseClicked

    private void jt_tablaInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tablaInformacionMouseClicked
        int fila = jt_tablaInformacion.getSelectedRow();
        int columna = jt_tablaInformacion.getSelectedColumn();
        lbl_columna.setText(columna+"");
        lbl_fila.setText(fila+"");
        
        String valorSeleccionado = jt_tablaInformacion.getValueAt(fila, columna).toString();
       
        ArrayList<javax.swing.JLabel> etiquetas = new  ArrayList<javax.swing.JLabel>();
        etiquetas.add(lbl_nombreTabla);
        etiquetas.add(lbl_apellidoTabla);
        etiquetas.add(lbl_tipoTabla);
        
        lbl_nombreTabla.setText(valorSeleccionado);
         DefaultTableModel modeloTabla = (DefaultTableModel)jt_tablaInformacion.getModel();
         for (int i = 0; i < modeloTabla.getColumnCount(); i++) {
              String valorTemp = jt_tablaInformacion.getValueAt(fila, i).toString();
              // TODO: evitar que esta linea de outOfBounce cuando agregamos una columna adicional
              etiquetas.get(i).setText(valorTemp);
        }
    }//GEN-LAST:event_jt_tablaInformacionMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
         int fila = jt_tablaInformacion.getSelectedRow();
          DefaultTableModel modeloTabla = (DefaultTableModel)jt_tablaInformacion.getModel();
          modeloTabla.removeRow(fila);
          
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_editarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarTablaMouseClicked
      int fila = jt_tablaInformacion.getSelectedRow();
      int columna = jt_tablaInformacion.getSelectedColumn();
      
       DefaultTableModel modeloTabla = (DefaultTableModel)jt_tablaInformacion.getModel();
       modeloTabla.setValueAt("NUEVO VALOR!", fila, columna);
        
    }//GEN-LAST:event_btn_editarTablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarColumna;
    private javax.swing.JButton btn_cambiarColorbackground;
    private javax.swing.JButton btn_colorTexto;
    private javax.swing.JButton btn_editarTabla;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardarContenido;
    private javax.swing.JButton btn_guardarTamano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> jc_tipo;
    private javax.swing.JComboBox<String> jcb_estilo;
    private javax.swing.JDialog jd_pantalla;
    private javax.swing.JList<String> jl_listaPersonas;
    private javax.swing.JMenu jm_abrir;
    private javax.swing.JMenu jm_exportar;
    private javax.swing.JMenuBar jmb_menuPrincipal;
    private javax.swing.JMenuItem jmi_limpiar;
    private javax.swing.JPanel jp_agregar;
    private javax.swing.JPopupMenu jpm_menu2;
    private javax.swing.JPopupMenu jpm_menuEmergente;
    private javax.swing.JTable jt_tablaInformacion;
    private javax.swing.JLabel lbl_apellidoTabla;
    private javax.swing.JLabel lbl_columna;
    private javax.swing.JLabel lbl_dialog;
    private javax.swing.JLabel lbl_fila;
    private javax.swing.JLabel lbl_nombreSeleccionado;
    private javax.swing.JLabel lbl_nombreTabla;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JLabel lbl_tipoTabla;
    private javax.swing.JTextField txt_agregarNombre;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_contenido;
    private javax.swing.JTextField txt_fuente;
    private javax.swing.JTextField txt_tamano;
    // End of variables declaration//GEN-END:variables
}
